'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''cbostate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbostate As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cbocity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbocity As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''txt_stationcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_stationcode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtfrom_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfrom_date As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnclick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnclick As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtpredicted_speed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpredicted_speed As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtactual_speed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtactual_speed As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtvariance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvariance As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnclear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnclear As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
